### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by sjogrenjohan** [sjogrenjohan/TechStore#5]
Skapa en navbar med titeln "TechStore" som är klickbar och tar en till startsidan, titeln ska ligga till vänster. Till höger ska en kundvagnsikon finnas som är klickbar och tar användaren till kundvagnssidan.

**Comment by PoturovicAnel** [comment]
Added Navbar need to fix colors

**Comment by sjogrenjohan** [comment]
Ni behöver fixa siffran bredvid kundvagnsikonen. Den ska ändras beroende på hur mycket vi lägger till i kundvagnen @PoturovicAnel @robi72

**Comment by PoturovicAnel** [comment]
done #14
